### ISSUE TITLE
Create UUID support

### ISSUE THREAD

**Issue by rtritto** [mongodb-js/query-parser#114]
`UUID` function should create correctly a new UUID (like _ObjectId_). [Source](https://www.mongodb.com/docs/manual/reference/method/UUID)

Bug is related to [ejson-shell-parser](https://www.npmjs.com/package/ejson-shell-parser).

```js
import parse from 'ejson-shell-parser';

const query = parse.default(
  '{ a: UUID() }',    // OR new UUID()
  { mode: 'strict' }
);
console.log(query);
```

## Actual
<details>
  <summary>Output</summary>

```console
C:\test-ejson-shell-parser\node_modules\ejson-shell-parser\dist\ejson-shell-parser.cjs.dev.js:157
    return new bson__namespace.Binary(Buffer.from(u.replace(/-/g, ''), 'hex'), 4);
                                                    ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at Function.UUID (C:\test-ejson-shell-parser\node_modules\ejson-shell-parser\dist\ejson-shell-parser.cjs.dev.js:157:53)
    at memberExpression (C:\test-ejson-shell-parser\node_modules\ejson-shell-parser\dist\ejson-shell-parser.cjs.dev.js:563:23)
    at walk (C:\test-ejson-shell-parser\node_modules\ejson-shell-parser\dist\ejson-shell-parser.cjs.dev.js:618:14)
    at C:\test-ejson-shell-parser\node_modules\ejson-shell-parser\dist\ejson-shell-parser.cjs.dev.js:624:20
    at Array.forEach (<anonymous>)
    at walk (C:\test-ejson-shell-parser\node_modules\ejson-shell-parser\dist\ejson-shell-parser.cjs.dev.js:622:23)
    at executeAST (C:\test-ejson-shell-parser\node_modules\ejson-shell-parser\dist\ejson-shell-parser.cjs.dev.js:640:14)
    at Object.parse [as default] (C:\test-ejson-shell-parser\node_modules\ejson-shell-parser\dist\ejson-shell-parser.cjs.dev.js:743:12)
    at file:///C:/test-ejson-shell-parser/index.js:6:28
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
```
</details>

## Expect
```console
{
  a: new Binary(Buffer.from("<uuid_with_no_hyphens>", "hex"), 4)
}
```

## How to fix
```diff
diff --git a/node_modules/ejson-shell-parser/dist/ejson-shell-parser.cjs.dev.js b/node_modules/ejson-shell-parser/dist/ejson-shell-parser.cjs.dev.js
index dd902df..07db965 100644
--- a/node_modules/ejson-shell-parser/dist/ejson-shell-parser.cjs.dev.js
+++ b/node_modules/ejson-shell-parser/dist/ejson-shell-parser.cjs.dev.js
@@ -2,6 +2,7 @@

 Object.defineProperty(exports, '__esModule', { value: true });

+var crypto = require('node:crypto');
 var acorn = require('acorn');
 var bson = require('bson');

@@ -154,7 +155,7 @@ var SCOPE = {
     return new bson__namespace.Binary(Buffer.from(d, 'base64'), t);
   },
   UUID: function UUID(u) {
-    return new bson__namespace.Binary(Buffer.from(u.replace(/-/g, ''), 'hex'), 4);
+    return new bson__namespace.Binary(Buffer.from((u || crypto.randomUUID()).replace(/-/g, ''), 'hex'), 4);
   },
   Code: function Code(c, s) {
     return new bson__namespace.Code(c, s);
diff --git a/node_modules/ejson-shell-parser/dist/ejson-shell-parser.cjs.prod.js b/node_modules/ejson-shell-parser/dist/ejson-shell-parser.cjs.prod.js
index dd902df..07db965 100644
--- a/node_modules/ejson-shell-parser/dist/ejson-shell-parser.cjs.prod.js
+++ b/node_modules/ejson-shell-parser/dist/ejson-shell-parser.cjs.prod.js
@@ -2,6 +2,7 @@

 Object.defineProperty(exports, '__esModule', { value: true });

+var crypto = require('node:crypto');
 var acorn = require('acorn');
 var bson = require('bson');

@@ -154,7 +155,7 @@ var SCOPE = {
     return new bson__namespace.Binary(Buffer.from(d, 'base64'), t);
   },
   UUID: function UUID(u) {
-    return new bson__namespace.Binary(Buffer.from(u.replace(/-/g, ''), 'hex'), 4);
+    return new bson__namespace.Binary(Buffer.from((u || crypto.randomUUID()).replace(/-/g, ''), 'hex'), 4);
   },
   Code: function Code(c, s) {
     return new bson__namespace.Code(c, s);
```

**Comment by rtritto** [comment]
Closed because it's moved to https://github.com/mongodb-js/ejson-shell-parser/issues/153
